Added IntermediateOutputPath option to MonoAotCompiler task parameters
dotnet/BenchmarkDotNet pull request #1888
Opened 2022-01-06 21:29 UTC by naricc

This adds the `IntermediateOutputPath` parameter to the MonoAotCompiler task in generated projects that use the MonoAotLLVM toolchain. That parameter is now required.

fixes: https://github.com/dotnet/BenchmarkDotNet/issues/1887

2022-01-06 21:29 UTC, naricc commented
@adamsitnik

2022-01-10 14:03 UTC, adamsitnik requested changes
Please delete the `.BenchmarkDotNet.Samples.csproj.swp` file (for some reason I can't do it from GH anymore)

2022-01-10 18:04 UTC, naricc commented
> Please delete the `.BenchmarkDotNet.Samples.csproj.swp` file (for some reason I can't do it from GH anymore)

Done.

2022-01-10 19:08 UTC, adamsitnik commented
@naricc You have removed `BenchmarkDotNet.Samples.csproj.swp`, but added `samples/BenchmarkDotNet.Samples/.out.swp` and `samples/BenchmarkDotNet.Samples/out`. Could you please remove all temporary files?

2022-01-11 11:05 UTC, adamsitnik commented on src/BenchmarkDotNet/Toolchains/MonoAotLLVM/MonoAotLLVMBuilder.cs
> -        }
after the removal of all the custom logic, this type has became just a dummy wrapper for `DotNetCliBuilder`. Could you please remove it and use `DotNetCliBuilder` directly for the AOT toolchain?

https://github.com/dotnet/BenchmarkDotNet/blob/63e28c100a42a6492d09a0b93a8a4c141061bb0d/src/BenchmarkDotNet/Toolchains/MonoAotLLVM/MonoAotLLVMToolChain.cs#L20-L22

2022-01-11 18:04 UTC, adamsitnik approved these changes
LGTM, thank you @naricc !

2022-01-11 18:04 UTC, merged