Support required properties
dotnet/BenchmarkDotNet pull request #2579
Opened 2024-06-06 07:05 UTC by aelij

2024-06-07 07:26 UTC, adamsitnik commented
@aelij some of the tests are failing, PTAL.

2025-02-19 11:34 UTC, aelij commented
@adamsitnik Sorry the PR slipped my mind. All tests pass now, I took a different approach.

2025-03-29 04:57 UTC, timcassell requested changes

2025-03-29 04:57 UTC, timcassell commented on src/BenchmarkDotNet/Code/CodeGenerator.cs
> +                    .Select(parameter => $"{parameter.Name} = default"));
I think it would be better to assign the actual value, that way `init` will also work. You will also need to change the `GetParamsContent` implementation to skip instance values. A rename to `GetInstanceParams` and `GetStaticParams` would be in order as well.

2025-03-30 07:41 UTC, aelij commented on src/BenchmarkDotNet/Code/CodeGenerator.cs
> +                    .Select(parameter => $"{parameter.Name} = default"));
That's what I tried initially (see previous commit) but the problem is that dynamic parameters won't work since they require the instance.
Also `required` support is essential not to get nullable warnings, `init` is a less useful IMO.

2025-03-30 08:13 UTC, timcassell commented on src/BenchmarkDotNet/Code/CodeGenerator.cs
> +                    .Select(parameter => $"{parameter.Name} = default"));
I can't see your initial commit. Are you referring to ParamsSource?

2025-03-30 08:19 UTC, aelij commented on src/BenchmarkDotNet/Code/CodeGenerator.cs
> +                    .Select(parameter => $"{parameter.Name} = default"));
I forced-pushed, it's in the PR history:
https://github.com/dotnet/BenchmarkDotNet/pull/2579/commits/469f034adf1722c4069109ac96efc125fc53333a
Yes, ParamsSource

2025-03-30 08:20 UTC, aelij commented on src/BenchmarkDotNet/Code/CodeGenerator.cs
> +                    .Select(parameter => $"{parameter.Name} = default"));
Sorry it's this one - https://github.com/dotnet/BenchmarkDotNet/commit/32495a953cb473a053bce18a944c738986b05818

2025-03-30 08:20 UTC, aelij commented on src/BenchmarkDotNet/Code/CodeGenerator.cs
> +                    .Select(parameter => $"{parameter.Name} = default"));
I even named the methods as you suggested :)

2025-03-30 21:33 UTC, timcassell approved these changes
Since the "SmartParameter" supports instance methods, it looks like this is the only way to do this. Thanks @aelij!

2025-03-30 21:34 UTC, merged

2025-03-30 21:35 UTC, timcassell commented on src/BenchmarkDotNet/Code/CodeGenerator.cs
> +                    .Select(parameter => $"{parameter.Name} = default"));
I agree, `init` doesn't seem particularly useful for benchmarks. It just would've been nice to support it "for free" if it was possible.

2025-03-30 21:39 UTC, timcassell commented
@aelij I just realized after merging that you didn't add tests for InProcess toolchains. Would you mind doing a follow-up to add those?

2025-03-31 08:00 UTC, aelij commented
Sure

2025-03-31 08:11 UTC, timcassell commented
InProcessTest and InProcessEmitTest