Use ArtifactsPath
dotnet/BenchmarkDotNet pull request #2676
Opened 2024-12-14 16:00 UTC by timcassell

Fixes #2425
Fixes #2664

Note about the implementation - we set `ArtifactsPath` if the dotnet sdk used supports it (v8.0 or higher). Older sdks still use the same build logic as previous, and as far as I could find out, it's the best we can do for those older sdks.

2025-01-27 18:32 UTC, timcassell commented
@adamsitnik Based on your comment https://github.com/dotnet/BenchmarkDotNet/issues/2693#issuecomment-2615638065, should we just always use ArtifactsPath and not worry about older sdks here?

2025-05-01 07:06 UTC, filzrev commented
I want to use this PR feature for benchmarks that use multi NuGet versions.

Is it possible to raise priority for review/merge?
And available as nightly build package?

2025-05-01 14:10 UTC, AndreyAkinshin requested changes
The end of support for .NET SDK 7.0 is May 14, 2024, which is about a year away. I suggest dropping support for .NET SDK 7 and requiring .NET SDK 8 or higher. This change would allow us to use ArtifactsPath everywhere by default, eliminating the need to pass `useArtifactsPath` repeatedly. Additionally, we should implement a warning for users attempting to run BenchmarkDotNet with older versions of the SDK.

2025-05-02 01:36 UTC, timcassell commented
Updated to your feedback. If we merge #2721, we can update the warning message to tell the user to disable parallel builds (or we could do it automatically).

2025-05-02 01:55 UTC, timcassell commented on src/BenchmarkDotNet/Validators/DotNetSdkValidator.cs
> +            else if (requiredSdkVersion.Major < 8)
Upon review, I think this check will always fail. I'm not sure how to determine whether the dotnet core sdk will successfully use ArtifactsPath when building older tfms. @rainersigwald Does sdk 8+ always use ArtifactsPath, or does it delegate the build to the older sdks?

2025-05-11 21:07 UTC, AndreyAkinshin approved these changes

2025-05-12 00:18 UTC, merged